output: "noisy_runs.jsonl"
damage_cases:
  - # Element 0 with 5% reduction
    - element: 0
      factor: 0.05  # 5% reduction in stiffness
  - # Element 0 with 10% reduction
    - element: 0
      factor: 0.1  # 10% reduction in stiffness
  - # Element 0 with 20% reduction
    - element: 0
      factor: 0.2  # 20% reduction in stiffness
  - # Element 4 with 5% reduction
    - element: 4
      factor: 0.05  # 5% reduction in stiffness
  - # Element 4 with 10% reduction
    - element: 4
      factor: 0.1  # 10% reduction in stiffness
  - # Element 4 with 20% reduction
    - element: 4
      factor: 0.2  # 20% reduction in stiffness